import {
  Tenant,
  Profile,
  Customer,
  Service,
  Professional,
  Appointment,
} from '../types';

export const initialTenant: Tenant = {
  id: 'tenant-1001',
  name: 'Studio Prime & Estética',
  slug: 'studio-prime',
  plan: 'pro',
  business_type: 'beauty_salon',
  phone: '11988887777',
  email: 'contato@studioprime.com.br',
  address: 'Av. Paulista, 1500 - Sala 42, São Paulo - SP',
  settings: {
    opening_time: '08:00',
    closing_time: '20:00',
    interval_minutes: 30,
    allow_online_booking: true,
  },
  created_at: new Date().toISOString(),
};

export const initialProfiles: Profile[] = [
  {
    id: 'prof-user-1',
    user_id: 'user-owner-1',
    tenant_id: 'tenant-1001',
    full_name: 'Camila Albuquerque',
    role: 'owner',
    email: 'admin@agendaai.com',
    phone: '11999998888',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-user-2',
    user_id: 'user-prof-2',
    tenant_id: 'tenant-1001',
    full_name: 'Lucas Ferreira',
    role: 'professional',
    email: 'lucas@agendaai.com',
    phone: '11987654321',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-user-3',
    user_id: 'user-rec-3',
    tenant_id: 'tenant-1001',
    full_name: 'Mariana Ramos',
    role: 'receptionist',
    email: 'mariana@agendaai.com',
    phone: '11977776666',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const initialProfessionals: Professional[] = [
  {
    id: 'pro-1',
    tenant_id: 'tenant-1001',
    name: 'Camila Albuquerque',
    email: 'camila@studioprime.com.br',
    phone: '11999998888',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'Master Stylist & Esteticista',
    specialties: ['Corte & Visagismo', 'Coloração', 'Harmonização Facial'],
    commission_percentage: 45,
    color: '#6366f1',
    is_active: true,
    working_hours: {
      start: '09:00',
      end: '19:00',
      days_of_week: [1, 2, 3, 4, 5, 6],
    },
  },
  {
    id: 'pro-2',
    tenant_id: 'tenant-1001',
    name: 'Lucas Ferreira',
    email: 'lucas@studioprime.com.br',
    phone: '11987654321',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'Barbeiro & Visagista',
    specialties: ['Corte Masculino', 'Barboterapia', 'Tratamento Capilar'],
    commission_percentage: 50,
    color: '#06b6d4',
    is_active: true,
    working_hours: {
      start: '10:00',
      end: '20:00',
      days_of_week: [2, 3, 4, 5, 6],
    },
  },
  {
    id: 'pro-3',
    tenant_id: 'tenant-1001',
    name: 'Beatriz Lima',
    email: 'beatriz@studioprime.com.br',
    phone: '11977771122',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Nail Designer & Podóloga',
    specialties: ['Alongamento em Gel', 'Manicure Russa', 'Spa dos Pés'],
    commission_percentage: 40,
    color: '#ec4899',
    is_active: true,
    working_hours: {
      start: '09:00',
      end: '18:00',
      days_of_week: [1, 2, 3, 4, 5, 6],
    },
  },
  {
    id: 'pro-4',
    tenant_id: 'tenant-1001',
    name: 'Rafael Santos',
    email: 'rafael@studioprime.com.br',
    phone: '11988882233',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Terapeuta Capilar & Massoterapeuta',
    specialties: ['Massagem Relaxante', 'Drenagem Linfática', 'Detox Capilar'],
    commission_percentage: 40,
    color: '#10b981',
    is_active: true,
    working_hours: {
      start: '09:00',
      end: '18:00',
      days_of_week: [1, 2, 3, 4, 5],
    },
  },
];

export const initialServices: Service[] = [
  {
    id: 'srv-1',
    tenant_id: 'tenant-1001',
    name: 'Corte Feminino & Escova Modeladora',
    description: 'Lavagem especial com massagem capilar, corte visagista e finalização com escova.',
    category: 'Cabelo',
    price: 140.0,
    duration_minutes: 60,
    is_active: true,
    color: '#6366f1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-2',
    tenant_id: 'tenant-1001',
    name: 'Corte Masculino Premium + Lavagem',
    description: 'Corte tesoura/máquina, acabamento na navalha e finalização com pomada matte.',
    category: 'Barbearia',
    price: 75.0,
    duration_minutes: 45,
    is_active: true,
    color: '#06b6d4',
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-3',
    tenant_id: 'tenant-1001',
    name: 'Barboterapia com Toalha Quente',
    description: 'Esfoliação facial, hidratação profunda com óleos essenciais e toalha vaporizada.',
    category: 'Barbearia',
    price: 65.0,
    duration_minutes: 30,
    is_active: true,
    color: '#06b6d4',
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-4',
    tenant_id: 'tenant-1001',
    name: 'Manicure & Pedicure Completa',
    description: 'Cutilagem cutilada, esmaltação premium e hidratação das cutículas.',
    category: 'Unhas',
    price: 85.0,
    duration_minutes: 60,
    is_active: true,
    color: '#ec4899',
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-5',
    tenant_id: 'tenant-1001',
    name: 'Alongamento em Gel (Fibra de Vidro)',
    description: 'Extensão estruturada de unhas com acabamento natural e esmaltação em gel.',
    category: 'Unhas',
    price: 220.0,
    duration_minutes: 120,
    is_active: true,
    color: '#ec4899',
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-6',
    tenant_id: 'tenant-1001',
    name: 'Limpeza de Pele Profunda com Peeling',
    description: 'Remoção de cravos, extração ultrassônica, máscara de argila e fototerapia LED.',
    category: 'Estética Facial',
    price: 180.0,
    duration_minutes: 90,
    is_active: true,
    color: '#8b5cf6',
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-7',
    tenant_id: 'tenant-1001',
    name: 'Mechas Criativas / Morena Iluminada',
    description: 'Técnica personalizada com plex protetor, tonalização e tratamento reconstrutor.',
    category: 'Cabelo',
    price: 480.0,
    duration_minutes: 180,
    is_active: true,
    color: '#6366f1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-8',
    tenant_id: 'tenant-1001',
    name: 'Massagem Relaxante com Pedras Quentes',
    description: 'Alívio de tensões musculares, aromaterapia e termoterapia corporal.',
    category: 'Corporal',
    price: 160.0,
    duration_minutes: 60,
    is_active: true,
    color: '#10b981',
    created_at: new Date().toISOString(),
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    tenant_id: 'tenant-1001',
    name: 'Juliana Mendes',
    phone: '11987651234',
    email: 'juliana.mendes@gmail.com',
    birth_date: '1992-05-14',
    notes: 'Prefere esmaltes tons nudes e café sem açúcar.',
    total_spent: 1250.0,
    appointments_count: 8,
    last_visit_at: '2026-08-25',
    is_vip: true,
    created_at: '2026-01-15',
  },
  {
    id: 'cust-2',
    tenant_id: 'tenant-1001',
    name: 'Rodrigo Antunes',
    phone: '11998884433',
    email: 'rodrigo.antunes@outlook.com',
    birth_date: '1988-11-20',
    notes: 'Corte degradê navalhado nº 0.5 e barba desenhada.',
    total_spent: 620.0,
    appointments_count: 5,
    last_visit_at: '2026-08-28',
    is_vip: false,
    created_at: '2026-03-10',
  },
  {
    id: 'cust-3',
    tenant_id: 'tenant-1001',
    name: 'Fernanda Oliveira',
    phone: '11971239876',
    email: 'fernanda.oli@empresa.com.br',
    birth_date: '1995-03-08',
    notes: 'Sensibilidade no couro cabeludo, usar linha vegana.',
    total_spent: 2450.0,
    appointments_count: 12,
    last_visit_at: '2026-08-29',
    is_vip: true,
    created_at: '2025-11-04',
  },
  {
    id: 'cust-4',
    tenant_id: 'tenant-1001',
    name: 'Gabriel Martins',
    phone: '11982345678',
    email: 'gabriel.martins@yahoo.com.br',
    birth_date: '1999-07-25',
    notes: 'Costuma agendar no final da tarde às sextas.',
    total_spent: 380.0,
    appointments_count: 3,
    last_visit_at: '2026-07-10',
    is_vip: false,
    created_at: '2026-05-18',
  },
  {
    id: 'cust-5',
    tenant_id: 'tenant-1001',
    name: 'Larissa Vasconcelos',
    phone: '11993456789',
    email: 'larissa.vasconcelos@gmail.com',
    birth_date: '1990-09-30',
    notes: 'Faz manutenção de fibra a cada 20 dias.',
    total_spent: 1780.0,
    appointments_count: 9,
    last_visit_at: '2026-08-26',
    is_vip: true,
    created_at: '2026-02-01',
  },
  {
    id: 'cust-6',
    tenant_id: 'tenant-1001',
    name: 'Bruno Carvalho',
    phone: '11976543210',
    email: 'bruno.c@gmail.com',
    birth_date: '1985-02-17',
    notes: 'Cliente inativo há mais de 70 dias. Enviar cupom.',
    total_spent: 210.0,
    appointments_count: 2,
    last_visit_at: '2026-06-15',
    is_vip: false,
    created_at: '2026-04-12',
  },
  {
    id: 'cust-7',
    tenant_id: 'tenant-1001',
    name: 'Patricia Souza',
    phone: '11984561230',
    email: 'patricia.souza@gmail.com',
    birth_date: '1987-12-05',
    notes: 'Gosta de atendimento pontual.',
    total_spent: 890.0,
    appointments_count: 6,
    last_visit_at: '2026-08-18',
    is_vip: false,
    created_at: '2026-03-22',
  },
];

// Helper to get today's date formatted as YYYY-MM-DD
export function getTodayDateString(): string {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export const initialAppointments: Appointment[] = [
  {
    id: 'apt-1',
    tenant_id: 'tenant-1001',
    customer_id: 'cust-1',
    customer_name: 'Juliana Mendes',
    customer_phone: '11987651234',
    service_id: 'srv-1',
    service_name: 'Corte Feminino & Escova Modeladora',
    service_price: 140.0,
    professional_id: 'pro-1',
    professional_name: 'Camila Albuquerque',
    date: getTodayDateString(),
    start_time: '09:00',
    end_time: '10:00',
    duration_minutes: 60,
    status: 'completed',
    payment_method: 'pix',
    total_price: 140.0,
    notes: 'Cliente pontual.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'apt-2',
    tenant_id: 'tenant-1001',
    customer_id: 'cust-2',
    customer_name: 'Rodrigo Antunes',
    customer_phone: '11998884433',
    service_id: 'srv-2',
    service_name: 'Corte Masculino Premium + Lavagem',
    service_price: 75.0,
    professional_id: 'pro-2',
    professional_name: 'Lucas Ferreira',
    date: getTodayDateString(),
    start_time: '10:00',
    end_time: '10:45',
    duration_minutes: 45,
    status: 'confirmed',
    payment_method: 'credit_card',
    total_price: 75.0,
    notes: 'Degradê baixo.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'apt-3',
    tenant_id: 'tenant-1001',
    customer_id: 'cust-3',
    customer_name: 'Fernanda Oliveira',
    customer_phone: '11971239876',
    service_id: 'srv-7',
    service_name: 'Mechas Criativas / Morena Iluminada',
    service_price: 480.0,
    professional_id: 'pro-1',
    professional_name: 'Camila Albuquerque',
    date: getTodayDateString(),
    start_time: '13:30',
    end_time: '16:30',
    duration_minutes: 180,
    status: 'confirmed',
    payment_method: 'unpaid',
    total_price: 480.0,
    notes: 'Retocar raiz e hidratar.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'apt-4',
    tenant_id: 'tenant-1001',
    customer_id: 'cust-5',
    customer_name: 'Larissa Vasconcelos',
    customer_phone: '11993456789',
    service_id: 'srv-5',
    service_name: 'Alongamento em Gel (Fibra de Vidro)',
    service_price: 220.0,
    professional_id: 'pro-3',
    professional_name: 'Beatriz Lima',
    date: getTodayDateString(),
    start_time: '14:00',
    end_time: '16:00',
    duration_minutes: 120,
    status: 'pending',
    payment_method: 'unpaid',
    total_price: 220.0,
    notes: 'Agendou pelo site.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'apt-5',
    tenant_id: 'tenant-1001',
    customer_id: 'cust-4',
    customer_name: 'Gabriel Martins',
    customer_phone: '11982345678',
    service_id: 'srv-3',
    service_name: 'Barboterapia com Toalha Quente',
    service_price: 65.0,
    professional_id: 'pro-2',
    professional_name: 'Lucas Ferreira',
    date: getTodayDateString(),
    start_time: '17:00',
    end_time: '17:30',
    duration_minutes: 30,
    status: 'pending',
    payment_method: 'unpaid',
    total_price: 65.0,
    notes: 'Primeira vez no estabelecimento.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'apt-6',
    tenant_id: 'tenant-1001',
    customer_id: 'cust-7',
    customer_name: 'Patricia Souza',
    customer_phone: '11984561230',
    service_id: 'srv-6',
    service_name: 'Limpeza de Pele Profunda com Peeling',
    service_price: 180.0,
    professional_id: 'pro-1',
    professional_name: 'Camila Albuquerque',
    date: getTodayDateString(),
    start_time: '17:30',
    end_time: '19:00',
    duration_minutes: 90,
    status: 'confirmed',
    payment_method: 'pix',
    total_price: 180.0,
    notes: 'Pele mista.',
    created_at: new Date().toISOString(),
  },
];
